### PR TITLE
Adding CI 

### PR DESCRIPTION
**Pull request by shimont**
I've added a CI process using GitHub actions

### CODE REVIEW

**Comment by geongeorge** [comment]
Okay I'm not embarrassed to say this- I've never done CI before 🙌
Can you give me a bit more context and use?

**Comment by geongeorge** [comment]
I have never done CI before. A little explanation would be helpful

**Comment by shimont** [comment]
CI stands for Continues Integration. Now every pull request will automatically run basic build tests
`yarn install`
`yarn build`

**Comment by geongeorge** [comment]
Thanks. Figured that out.
we added linting as well

**Pull request merged**
