### PR TITLE
Added regex stanza for UUID

### PR DESCRIPTION
**Pull request by alex-hofmann**
Add stanza to regexdata.json for identifying UUIDs

### CODE REVIEW

**Comment by alex-hofmann** [comment]
Not sure if this is something you'd want to add, but it may be useful!

**Comment by geongeorge** [comment]
Looks great! It'd be nice if there is an explanation what a UUID is in the description

**Comment by alex-hofmann** [comment]
Cool! I added some information pulled from the [UUID wiki](https://en.wikipedia.org/wiki/Universally_unique_identifier). Let me know if you think there's too much info now.

> This expression can be used to find or validate a UUID. UUIDs are often used to uniquely identify information in computer systems. A UUID is a 128-bit number represented, textually, in 16 octets as 32 hexadecimal (base-16) digits. These 32 digits are displayed in 5 groups separated by hyphens, in the form 8-4-4-4-12, for a total of 36 characters. You may edit the regex to your liking for removing hyphens.

**Comment by geongeorge** [comment]
This looks cool 👍@alex-hofmann Merged

**Pull request merged**
