### PR TITLE
Added PAN number extractor from GSTIN input

### PR DESCRIPTION
**Pull request by Pragalbha-Patil**
pan-from-gstin regex can extract Permanent Account number (PAN) from GSTIN.

### CODE REVIEW

**Comment by geongeorge** [comment]
Thanks, looks cool.
Can you make this PR into the develop branch?

**Comment by geongeorge** [comment]
Looks good to me :)

**Comment by geongeorge** [comment]
@Pragalbha-Patil can you explain this "Extract permanent account number (PAN) from GSTIN number" ?

This expression can match pan number group in a GST number?
Does all gst numbers contain pan numbers in them?
Can you provide examples


https://dev.ihateregex.io/expr/pan-from-gstin
(add the m flag for multiline, I'll fix this when merging)

**Comment by Pragalbha-Patil** [comment]
> @Pragalbha-Patil can you explain this "Extract permanent account number (PAN) from GSTIN number" ?
> 
> This expression can match pan number group in a GST number?
> Does all gst numbers contain pan numbers in them?
> Can you provide examples
> 
> https://dev.ihateregex.io/expr/pan-from-gstin
> (add the m flag for multiline, I'll fix this when merging)

1. Yes, the regex matches PAN number group in a GST number
2. Yes, every GST number has 10 digit PAN number in it.
3. Example: 22ABCDE1234F1Z5 where (ABCDE1234F) is a 10 digit PAN number.

**Pull request merged**
